### ISSUE TITLE
bug: 我看到了奇怪的東西

### ISSUE THREAD

**Issue by YJack0000** [CeranaPOS/cloud-function#19]
https://github.com/CeranaPOS/cloud-function/blob/5723bd02b7cad14c33293adddc7bfeb1606a5fe3/functions/model/material/userMaterial.model.js#L27

@Lanznx J個地方貌似把material-record跟user-material混在一起了，不太懂要做啥。

**Comment by Lanznx** [comment]
![image](https://user-images.githubusercontent.com/96360357/204841074-40de62ee-aefa-41fa-8dbf-18b3aade43fa.png)
在打purchaseOrder 這個 post 的時候會需要
1. 新增一筆 purchase order 
2. 調整 material 的數量

所以會動到 purchaseOrder (暫時叫做material record) 跟 userMaterial

**Comment by Lanznx** [comment]
@YJack0000

**Comment by YJack0000** [comment]
OK了解，我新增了兩個 function 分別是 addMaterialModel 和 updateMaterialCountModel。你覺得是不是要改成只有 updateMaterialCountModel?
主要是當使用者新增一個 material 了時候，同時要更新 material 被使用過的數量（occurCount）和 user-material 的資料。
照你的 update 方式可能就創建跟更新就直接弄一起就好了？

但我在想會不會在 model 層把邏輯寫分散會比較好，在 controller 那邊再判斷是不是第一次遇到。

**Comment by YJack0000** [comment]
@Lanznx

**Comment by YJack0000** [comment]
@grace0950 老江湖有啥看法？

**Comment by grace0950** [comment]
如果Model是代表對DB的操作，因為是用firebase，所以如果material不存在，update時會fail，所以我覺得可以分成兩個Model，會比較乾淨。

**Comment by Lanznx** [comment]
> OK了解，我新增了兩個 function 分別是 addMaterialModel 和 updateMaterialCountModel。你覺得是不是要改成只有 updateMaterialCountModel? 主要是當使用者新增一個 material 了時候，同時要更新 material 被使用過的數量（occurCount）和 user-material 的資料。 照你的 update 方式可能就創建跟更新就直接弄一起就好了？
> 
> 但我在想會不會在 model 層把邏輯寫分散會比較好，在 controller 那邊再判斷是不是第一次遇到。

@YJack0000 
我那時候確實有在想要不要再把邏輯抽上來一層
因為 model 應該只負責做跟資料庫的互動就好
但那時候覺得太麻煩ㄌ 加上邏輯不多所以就放在那邊
覺得需要的話可以改沒問題

**Comment by YJack0000** [comment]
我覺得改個 反正也就多一個function 這樣之後比較好分
