### ISSUE TITLE
bug: get order fail

### ISSUE THREAD

**Issue by YJack0000** [CeranaPOS/cloud-function#34]
<img width="900" alt="Screen Shot 2022-12-06 at 5 01 38 PM" src="https://user-images.githubusercontent.com/49984479/205866943-52e4321a-cb13-4141-bd75-2bf27177fdf0.png">

看起來像是後端執行了時候 catch 到 error，可能檢查一下哪裡出問題。

@Lanznx

**Comment by Lanznx** [comment]
@YJack0000 我在本地側很正常誒
而且他有錯誤的話應該會放在 `err` 
但上面的錯誤是空的
懷疑是 firebase 在搞？
